#!/usr/bin/env bash
# Terminate script if there is an error

set -e

echo -e "\e[36m Running PEP8...\e[0m"
pep8 --show-source --show-pep8 PyTree.py
echo -e "\e[36m Running PyLint...\e[0m"
pylint PyTree.py